### ISSUE TITLE
Implement RFC0041: Use Direct Processes and exec.d

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/poetry-run#37]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0041-direct.md)

### Summary

All Paketo buildpacks language families must update their buildpacks to use direct process types. There is an upstream change that will only permit direct process types.

Buildpack authors need to review buildpacks and take the following actions:

- Look for the usage of profile.d scripts and convert them to exec.d binaries
- Update any buildpacks that write process types and set `direct: true`. While doing this, evaluate the command being generated and determine if it requires a shell. If it can be done without a shell, make that change. If it requires a shell, you will need to wrap the original command with a call to the shell. For example: `bash -c '<cmd>'` (or some other shell). Please note that requiring a shell prohibits the buildpack from running in environments like tiny where there is no shell available.
- Investigate if users of the buildpack are likely to use `.profile` scripts. These will no longer be supported after switching to the direct process type. If this is common for buildpack users, then document that `.profile` is no longer supported and document the actions one could take to replace that script (like using procfile or environment-variables buildpacks). Buildpack language families may choose to wait if this is deemed a major impact to users until there is an acceptable solution (such as a profile buildpack).

**Comment by robdimsdale** [comment]
As of #41 we set all launch processes to: `direct: true`. We also do not directly invoke any shells. Additionally, we have no evidence to suggest that consumers of this buildpack are likely to use `.profile` scripts.

The only outstanding issue that I see would be that if the user tried to invoke a command that relied on a shell or set a run script that invoked a shell, that may not work in environments that do not have a shell (like tiny). However, I think this potential issue is outside of the scope of what is being discussed here, so I do not think it needs to be a blocker.

I'm closing this issue as I believe this buildpack now meets all the requirements.
